# Generated by Django 5.0.6 on 2024-06-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_product_thumbnails_photo_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnails",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
