# Generated by Django 5.0.6 on 2024-06-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_alter_product_thumbnails"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={
                "ordering": ["id"],
                "verbose_name": "Zdjęcie",
                "verbose_name_plural": "Zdjęcia",
            },
        ),
        migrations.AlterModelOptions(
            name="thumbnail",
            options={
                "ordering": ["id"],
                "verbose_name": "Miniatura",
                "verbose_name_plural": "Miniatury",
            },
        ),
        migrations.RenameField(
            model_name="photo",
            old_name="thumbnails_cache",
            new_name="thumbnails",
        ),
    ]
