# Generated by Django 5.0.6 on 2024-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_alter_photo_options_alter_thumbnail_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="thumbnails",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
