# Generated by Django 5.0.6 on 2024-07-01 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_thumbnail_height_thumbnail_width"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thumbnail",
            name="size",
        ),
    ]
