# Generated by Django 5.0.6 on 2024-07-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "web",
            "0025_alter_thumbnail_options_photo_order_thumbnail_main_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
