# Generated by Django 5.0.6 on 2024-07-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0027_photo_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thumbnail",
            options={
                "ordering": ["-main", "order", "id"],
                "verbose_name": "Miniatura",
                "verbose_name_plural": "Miniatury",
            },
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="alt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
