# Generated by Django 5.0.6 on 2024-07-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0030_category_image_category_thumbnails"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="accessories",
            field=models.ManyToManyField(
                blank=True,
                related_name="is_accessory_for",
                to="web.product",
                verbose_name="Akcesoria dla produktu: ",
            ),
        ),
    ]
