# Generated by Django 5.0.6 on 2024-07-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0032_brand_material_size_tag_product_brand_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["name"],
                "verbose_name": "Marka",
                "verbose_name_plural": "Marki",
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={
                "ordering": ["name"],
                "verbose_name": "Materiał",
                "verbose_name_plural": "Materiały",
            },
        ),
        migrations.AlterModelOptions(
            name="size",
            options={
                "ordering": ["name"],
                "verbose_name": "Rozmiar",
                "verbose_name_plural": "Rozmiary",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.brand",
                verbose_name="Marka",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.material",
                verbose_name="Materiał",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.size",
                verbose_name="Rozmiar",
            ),
        ),
    ]
