# Generated by Django 5.0.6 on 2024-07-04 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0033_alter_brand_options_alter_material_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nazwa wariantu"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=1, verbose_name="Kolejność"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Kolor",
                    ),
                ),
                ("qty", models.IntegerField(default=0, verbose_name="Ilość")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="variants",
                        verbose_name="Zdjęcie wariantu",
                    ),
                ),
                (
                    "thumbnails",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="Czy główny"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.material",
                        verbose_name="Materiał",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="web.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.size",
                        verbose_name="Rozmiar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wariant produktu",
                "verbose_name_plural": "Warianty produktów",
                "ordering": ["name"],
            },
        ),
    ]
