# Generated by Django 5.0.6 on 2024-07-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0034_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.IntegerField(
                choices=[
                    (0, "Brak koloru"),
                    (1, "Biały"),
                    (2, "Szary"),
                    (3, "Czerwony"),
                    (4, "Niebieski"),
                    (5, "Zielony"),
                    (6, "Żółty"),
                    (7, "Pomarańczowy"),
                    (8, "Brązowy"),
                    (9, "Różowy"),
                    (10, "Fioletowy"),
                    (11, "Beżowy"),
                    (12, "Czarny"),
                ],
                default=0,
                verbose_name="Kolor wariantu",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="color",
            field=models.IntegerField(
                choices=[
                    (0, "Brak koloru"),
                    (1, "Biały"),
                    (2, "Szary"),
                    (3, "Czerwony"),
                    (4, "Niebieski"),
                    (5, "Zielony"),
                    (6, "Żółty"),
                    (7, "Pomarańczowy"),
                    (8, "Brązowy"),
                    (9, "Różowy"),
                    (10, "Fioletowy"),
                    (11, "Beżowy"),
                    (12, "Czarny"),
                ],
                default=0,
                verbose_name="Kolor wariantu",
            ),
        ),
    ]
