# Generated by Django 5.0.6 on 2024-07-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0035_product_color_alter_productvariant_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_thumbnails",
                to="web.productvariant",
            ),
        ),
    ]
