# Generated by Django 5.0.6 on 2024-07-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0036_thumbnail_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="is_variant",
            field=models.BooleanField(default=False),
        ),
    ]
