# Generated by Django 5.0.6 on 2024-07-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0037_thumbnail_is_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="web.productvariant",
            ),
        ),
    ]
