# Generated by Django 5.0.6 on 2024-07-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0038_photo_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
