# Generated by Django 5.0.6 on 2024-08-06 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0042_alter_productvariant_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nazwa opcji"
                    ),
                ),
            ],
            options={
                "verbose_name": "Opcja produktu",
                "verbose_name_plural": "Opcje produktu",
            },
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "ordering": ["-is_main", "order", "name"],
                "verbose_name": "Wariant produktu",
                "verbose_name_plural": "Warianty produktów",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_options",
            field=models.ManyToManyField(
                blank=True, to="web.productoption", verbose_name="Opcje cech"
            ),
        ),
        migrations.CreateModel(
            name="ProductOptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nazwa elementu opcji"
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="web.productoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Element opcji",
                "verbose_name_plural": "Elementy opcji",
            },
        ),
    ]
