# Generated by Django 5.0.6 on 2024-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0043_productoption_alter_productvariant_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productoption",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Opcja produktu",
                "verbose_name_plural": "Opcje produktu",
            },
        ),
        migrations.AlterModelOptions(
            name="productoptionitem",
            options={
                "verbose_name": "Opcje element",
                "verbose_name_plural": "Opcje elementy",
            },
        ),
        migrations.AddField(
            model_name="productoption",
            name="order",
            field=models.IntegerField(default=1, verbose_name="Kolejność"),
        ),
    ]
