# Generated by Django 5.0.6 on 2024-08-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0046_remove_product_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_options",
                to="web.productoption",
            ),
        ),
    ]
