# Generated by Django 5.0.6 on 2024-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0047_alter_product_product_option"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="main",
        ),
        migrations.AddField(
            model_name="category",
            name="on_first_page",
            field=models.BooleanField(
                default=False, verbose_name="Czy widoczna na 1 stronie?"
            ),
        ),
    ]
