# Generated by Django 5.0.6 on 2024-08-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0049_product_on_first_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Tytuł"),
                ),
                ("description", models.TextField(verbose_name="Opis")),
                (
                    "image",
                    models.ImageField(
                        upload_to="heros", verbose_name="Zdjęcie"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=1, verbose_name="Kolejność"),
                ),
                (
                    "thumbnails",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Czy aktywny"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero",
                "verbose_name_plural": "Heroy",
                "ordering": ["order", "title"],
            },
        ),
    ]
