# Generated by Django 5.0.6 on 2024-08-08 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0050_hero"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="hero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hero_thumbnails",
                to="web.hero",
            ),
        ),
    ]
