# Generated by Django 5.0.6 on 2024-08-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0053_rename_org_oryg_image_thumbnail_oryg_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="slug",
            field=models.SlugField(
                default=1, max_length=100, unique=True, verbose_name="Slug"
            ),
            preserve_default=False,
        ),
    ]
