# Generated by Django 5.0.6 on 2024-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0055_alter_hero_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="oryg_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="heros",
                verbose_name="Zdjęcie",
            ),
        ),
    ]
