# Generated by Django 5.0.6 on 2024-08-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0056_alter_hero_oryg_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Shipment",
            new_name="Delivery",
        ),
    ]
