# Generated by Django 5.0.6 on 2024-08-19 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0057_rename_shipment_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="inpost_box",
            field=models.BooleanField(
                default=False, verbose_name="Czy dostawa to paczkomat Inpost?"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="oryg_image",
            field=models.ImageField(
                blank=True,
                upload_to="deliveries",
                verbose_name="Zdjęcie główne",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="thumbnails",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_thumbnails",
                to="web.delivery",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Czy aktywna?"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Cena promocyjna"
            ),
        ),
    ]
