# Generated by Django 5.0.6 on 2024-08-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0058_delivery_inpost_box_delivery_oryg_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="price_promo",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                verbose_name="Cena promocyjna",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="delivery",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Cena"
            ),
        ),
    ]
