# Generated by Django 5.0.6 on 2024-08-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0059_delivery_price_promo_alter_delivery_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
