# Generated by Django 5.0.6 on 2024-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0060_delivery_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="free_delivery",
            field=models.BooleanField(
                default=False, verbose_name="Darmowa dostawa"
            ),
        ),
    ]
