# Generated by Django 5.0.6 on 2024-08-19 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0061_product_free_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Kolejność"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="web.delivery",
                verbose_name="Sposób dostawy",
            ),
        ),
    ]
