# Generated by Django 5.0.6 on 2024-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0062_delivery_order_alter_order_delivery_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="in_store_pickup",
            field=models.BooleanField(
                default=False, verbose_name="Czy odbiór osobisty?"
            ),
        ),
    ]
