# Generated by Django 5.0.6 on 2024-08-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0063_delivery_in_store_pickup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nazwa"),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, null=True),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cena"
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=False, verbose_name="Czy to płatność online?"
                    ),
                ),
                (
                    "oryg_image",
                    models.ImageField(
                        blank=True,
                        upload_to="deliveries",
                        verbose_name="Zdjęcie główne",
                    ),
                ),
                (
                    "thumbnails",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Czy aktywna?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rodzaj płatności",
                "verbose_name_plural": "Rodzaj płatności",
                "ordering": ["order", "name"],
            },
        ),
    ]
