# Generated by Django 5.0.6 on 2024-08-19 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0064_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_thumbnails",
                to="web.payment",
            ),
        ),
    ]
