# Generated by Django 5.0.6 on 2024-08-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0066_alter_delivery_options_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="online_payment_upon_delivery",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_on_delivery",
            field=models.BooleanField(
                default=False, verbose_name="Czy to płatność przy odbiorze?"
            ),
        ),
    ]
