# Generated by Django 5.0.6 on 2024-08-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0068_hero_link_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="seo_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tekst SEO"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tekst SEO"
            ),
        ),
    ]
