# Generated by Django 5.0.6 on 2024-08-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0069_category_seo_text_product_seo_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_code",
            new_name="order_code_stripe",
        ),
        migrations.AlterField(
            model_name="order",
            name="client_address",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Adres klienta",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="web.payment",
                verbose_name="Sposób płatności",
            ),
        ),
    ]
