# Generated by Django 5.0.6 on 2024-08-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0070_rename_order_code_order_order_code_stripe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="inpost_box_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Id paczkomatu",
            ),
        ),
    ]
