# Generated by Django 5.0.6 on 2024-08-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0071_order_inpost_box_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart_items",
            field=models.JSONField(
                null=True, verbose_name="Produkty w koszyku"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cart_items_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Cena produktów",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Opłata za dostwę",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Opłata za płatność",
            ),
        ),
    ]
