# Generated by Django 5.0.6 on 2024-08-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0074_alter_order_amount_with_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Rabat",
            ),
        ),
    ]
