# Generated by Django 5.0.6 on 2024-08-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0079_profile_company_payer_profile_invoice_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="address",
            new_name="street",
        ),
    ]
