# Generated by Django 5.0.6 on 2024-08-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0080_rename_address_profile_street"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Miasto"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="company",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nazwa firmy",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="company_payer",
            field=models.TextField(
                blank=True, null=True, verbose_name="Płatnik"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="house_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Numer domu",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Miasto"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_house_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Numer domu",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_local_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Numer lokalu",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_postal_code",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Kod pocztowy",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_street",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ulica"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="local_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Numer lokalu",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Kod pocztowy",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="street",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ulica"
            ),
        ),
    ]
