# Generated by Django 5.0.6 on 2024-08-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0081_order_city_order_company_order_company_payer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="nip",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="NIP"
            ),
        ),
    ]
