# Generated by Django 5.0.6 on 2024-08-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0082_order_nip"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Opłacone"),
        ),
    ]
