# Generated by Django 5.0.6 on 2024-08-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0083_order_is_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="client_address",
        ),
    ]
