# Generated by Django 5.0.6 on 2024-09-02 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0084_remove_order_client_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="invoice",
            new_name="make_invoice",
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data utworzenia",
                    ),
                ),
                ("number", models.CharField(max_length=64)),
                (
                    "override_number",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Nadpisany numer faktury",
                    ),
                ),
                (
                    "override_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Nadpisana data faktury",
                    ),
                ),
                ("pdf", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Faktury",
                "ordering": ("-created_time",),
            },
        ),
    ]
