# Generated by Django 5.0.6 on 2024-09-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0085_rename_invoice_order_make_invoice_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_created",
            field=models.BooleanField(
                default=False, verbose_name="Faktura utworzona"
            ),
        ),
    ]
