# Generated by Django 5.0.6 on 2024-09-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0086_order_invoice_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="bank_transfer",
            field=models.BooleanField(
                default=False, verbose_name="Czy to przelew bankowy?"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_deferral",
            field=models.IntegerField(
                default=14, verbose_name="Dni na opłacenie"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="make_invoice",
            field=models.BooleanField(
                default=False, verbose_name="Generuj fakturę?"
            ),
        ),
    ]
