# Generated by Django 5.0.6 on 2024-09-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "web",
            "0087_payment_bank_transfer_payment_payment_deferral_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="invoice",
            new_name="make_invoice",
        ),
    ]
