# Generated by Django 5.0.6 on 2024-09-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0089_product_is_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="title_text",
        ),
        migrations.RemoveField(
            model_name="thumbnail",
            name="alt",
        ),
        migrations.RemoveField(
            model_name="thumbnail",
            name="title",
        ),
        migrations.AddField(
            model_name="category",
            name="image_alt",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tekst alternatywny",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tytuł zdjęcia",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="image_alt",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tekst alternatywny",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="image_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tytuł zdjęcia",
            ),
        ),
        migrations.AddField(
            model_name="hero",
            name="image_alt",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tekst alternatywny",
            ),
        ),
        migrations.AddField(
            model_name="hero",
            name="image_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tytuł zdjęcia",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="image_alt",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tekst alternatywny",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="image_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tytuł zdjęcia",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="image_alt",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tekst alternatywny",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="image_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tytuł zdjęcia",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_alt",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tekst alternatywny",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tytuł zdjęcia",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="image_alt",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tekst alternatywny",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="image_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tytuł zdjęcia",
            ),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="image_alt",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tekst alternatywny",
            ),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="image_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tytuł zdjęcia",
            ),
        ),
    ]
