# Generated by Django 5.0.6 on 2024-09-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0090_remove_photo_alt_text_remove_photo_title_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thumbnail",
            name="image_alt",
        ),
        migrations.RemoveField(
            model_name="thumbnail",
            name="image_title",
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="alt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
