# Generated by Django 5.0.6 on 2024-09-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0091_remove_thumbnail_image_alt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.AddField(
            model_name="category",
            name="item_label",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Etykieta w menu",
            ),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
