# Generated by Django 5.0.6 on 2024-09-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0093_alter_profile_nip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nip",
            field=models.CharField(
                blank=True, max_length=56, null=True, verbose_name="NIP"
            ),
        ),
    ]
