# Generated by Django 5.0.6 on 2024-09-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0094_alter_profile_nip"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="send_emails",
            field=models.BooleanField(
                default=False, verbose_name="Wysyłać maile"
            ),
        ),
    ]
