# Generated by Django 5.0.6 on 2024-09-09 14:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0095_profile_send_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Unikalny identyfikator",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
