# Generated by Django 5.0.6 on 2024-09-09 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0096_order_uid_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Unikalny identyfikator",
            ),
        ),
    ]
