# Generated by Django 5.0.6 on 2024-09-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0100_alter_invoice_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link do zamówienia"
            ),
        ),
    ]
