# Generated by Django 5.0.6 on 2024-09-09 18:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0101_order_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="uid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Unikalny identyfikator",
            ),
        ),
    ]
