# Generated by Django 5.0.6 on 2024-09-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0103_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thumbnails",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="web.article",
            ),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_thumbnails",
                to="web.article",
            ),
        ),
    ]
