# Generated by Django 5.0.6 on 2024-09-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0104_article_thumbnails_photo_article_thumbnail_article"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="image_oryg",
            new_name="oryg_image",
        ),
    ]
