# Generated by Django 5.0.6 on 2024-09-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0105_rename_image_oryg_article_oryg_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Opis"
            ),
        ),
    ]
