# Generated by Django 5.0.6 on 2024-09-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0107_rename_title_article_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="h1_tag",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nagłówek H1",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description",
            field=models.CharField(
                blank=True,
                max_length=160,
                null=True,
                verbose_name="Meta description",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_title",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Meta title"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="h1_tag",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tag H1"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.CharField(
                blank=True,
                max_length=160,
                null=True,
                verbose_name="Meta description dla produktu",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="Meta title dla produktu",
            ),
        ),
    ]
