# Generated by Django 5.0.6 on 2024-09-18 10:30

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0108_category_h1_tag_category_meta_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Artykuł",
                "verbose_name_plural": "Artykuły",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="modyfied_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data modyfikacji"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 9, 18, 10, 30, 39, 179266),
                verbose_name="Data utworzenia",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="modyfied_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data modyfikacji"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 9, 18, 10, 30, 42, 3203),
                verbose_name="Data utworzenia",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="modyfied_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data modyfikacji"
            ),
        ),
    ]
