# Generated by Django 5.0.6 on 2024-09-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0109_alter_article_options_article_modyfied_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="modyfied_date",
            new_name="modified_date",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="modyfied_date",
            new_name="modified_date",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="modyfied_date",
            new_name="modified_date",
        ),
    ]
