# Generated by Django 5.0.6 on 2024-09-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0111_order_prev_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="invoice_city",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Miasto na FV",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="invoice_house_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Numer domu na FV",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="invoice_local_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Numer lokalu na FV",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="invoice_postal_code",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Kod pocztowy na FV",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="invoice_city",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Miasto na FV",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="invoice_house_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Numer domu na FV",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="invoice_local_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Numer lokalu  na FV",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="invoice_postal_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="Kod pocztowy na FV",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="invoice_street",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Ulica na FV",
            ),
        ),
    ]
