# Generated by Django 5.0.6 on 2024-10-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0113_payment_price_promo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="google_product_category",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Kategoria produktu w Google Merchant",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="prev_status",
            field=models.IntegerField(
                choices=[
                    (0, "Nowe"),
                    (1, "W trakcie płatności"),
                    (2, "Płatności anulowana"),
                    (3, "Opłacone"),
                    (4, "Trwa weryfikacja płatności"),
                    (5, "Do zapłaty"),
                    (6, "Płatność nieudana"),
                    (7, "Błąd płatności Stripe"),
                    (8, "W trakcie realizacji"),
                    (9, "W dostawie"),
                    (10, "Dostarczone"),
                    (11, "Zwrócone"),
                    (12, "Gotowe do odbioru"),
                    (13, "Zrealizowane"),
                    (14, "Anulowane"),
                ],
                default=0,
                verbose_name="Poprzedni status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Nowe"),
                    (1, "W trakcie płatności"),
                    (2, "Płatności anulowana"),
                    (3, "Opłacone"),
                    (4, "Trwa weryfikacja płatności"),
                    (5, "Do zapłaty"),
                    (6, "Płatność nieudana"),
                    (7, "Błąd płatności Stripe"),
                    (8, "W trakcie realizacji"),
                    (9, "W dostawie"),
                    (10, "Dostarczone"),
                    (11, "Zwrócone"),
                    (12, "Gotowe do odbioru"),
                    (13, "Zrealizowane"),
                    (14, "Anulowane"),
                ],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
