# Generated by Django 5.0.6 on 2024-10-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0115_productreview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Opinia o produkcie",
                "verbose_name_plural": "Opinie o produkcie",
            },
        ),
        migrations.AddField(
            model_name="productprice",
            name="expired_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Data wygaśnięcia ceny",
            ),
        ),
    ]
