# Generated by Django 5.0.6 on 2024-10-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0116_alter_productreview_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productreview",
            old_name="comment",
            new_name="message",
        ),
        migrations.AddField(
            model_name="productreview",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Imię"
            ),
        ),
    ]
