# Generated by Django 5.0.6 on 2024-10-24 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0117_rename_comment_productreview_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["product"], name="web_product_product_d48a68_idx"
            ),
        ),
    ]
