# Generated by Django 5.0.6 on 2024-11-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0118_productreview_web_product_product_d48a68_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="photo_pk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_pk_thumbnails",
                to="web.photo",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_alt",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tekst alternatywny zdjęcia",
            ),
        ),
    ]
