# Generated by Django 5.0.6 on 2024-11-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0119_thumbnail_photo_pk_alter_product_image_alt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thumbnail",
            name="photo_pk",
        ),
    ]
