# Generated by Django 5.0.6 on 2026-07-09 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0120_remove_thumbnail_photo_pk"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileServiceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_keys_qty",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Minimalna liczba kluczy na dojazd bez dopłaty",
                    ),
                ),
                (
                    "min_stamp_order_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Minimalna wartość zamówienia na pieczątki bez dopłaty za dojazd",
                    ),
                ),
                (
                    "wholesale_qty",
                    models.PositiveIntegerField(
                        default=10,
                        verbose_name="Próg ilościowy do ceny hurtowej",
                    ),
                ),
                (
                    "wholesale_discount_percent",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Rabat hurtowy (%)"
                    ),
                ),
                (
                    "delivery_time_hours",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Czas dojazdu (w godzinach)"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Numer telefonu do kontaktu",
                    ),
                ),
                (
                    "whatsapp_url",
                    models.URLField(blank=True, verbose_name="Link WhatsApp"),
                ),
                (
                    "messenger_url",
                    models.URLField(blank=True, verbose_name="Link Messenger"),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_service_settings",
                        to="web.category",
                        verbose_name="Kategoria usługi mobilnej",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ustawienia usługi mobilnej",
                "verbose_name_plural": "Ustawienia usług mobilnych",
            },
        ),
    ]
