# Generated by Django 5.0.6 on 2026-07-10 13:05

import web.models.inquiries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0122_seed_mobile_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyPhotoInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=web.models.inquiries.key_photo_upload_path,
                        verbose_name="Zdjęcie klucza",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Telefon"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Notatka")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data zgłoszenia"
                    ),
                ),
                (
                    "handled",
                    models.BooleanField(
                        default=False, verbose_name="Obsłużone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zgłoszenie zdjęcia klucza",
                "verbose_name_plural": "Zgłoszenia zdjęć kluczy",
                "ordering": ["-created_date"],
            },
        ),
    ]
