# Generated by Django 5.0.6 on 2026-07-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0123_keyphotoinquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceLocality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        verbose_name="Nazwa miejscowości / dzielnicy",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "region_label",
                    models.CharField(
                        max_length=150,
                        verbose_name="Etykieta regionu (gmina / dzielnica)",
                    ),
                ),
                (
                    "local_note",
                    models.TextField(
                        verbose_name="Opis lokalny (unikalny fragment treści SEO)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kolejność"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywna"),
                ),
            ],
            options={
                "verbose_name": "Miejscowość obsługi mobilnej",
                "verbose_name_plural": "Miejscowości obsługi mobilnej",
                "ordering": ("order", "name"),
            },
        ),
    ]
