# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0125_seed_service_localities"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="pickup_only",
            field=models.BooleanField(
                default=False,
                verbose_name="Czy dostępna tylko dla odbioru osobistego?",
            ),
        ),
    ]
