# Generated by Django 5.0.6 on 2026-09-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0126_payment_pickup_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Tekst linku"
                    ),
                ),
                ("url", models.URLField(verbose_name="Adres URL")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Opis (aria-label)",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("partner", "Partner"),
                            ("author", "Twórca serwisu"),
                        ],
                        default="partner",
                        max_length=20,
                        verbose_name="Rodzaj",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kolejność"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Link w stopce",
                "verbose_name_plural": "Linki w stopce",
                "ordering": ("order", "name"),
            },
        ),
    ]
